`timescale 1ns/1ps
`default_nettype none

// Waveform multiplexer for one DDS phase stream.
// Generates sine through the pipelined CORDIC and aligns combinational square,
// triangle, and DC outputs to the same valid cycle.
module waveform_generator (
    input  logic                 i_clk,
    input  logic                 i_rst,

    input  logic                 i_phase_valid,
    input  dds_pkg::phase_t      i_phase,
    input  dds_pkg::waveform_t   i_waveform,

    output logic                 o_sample_valid,
    output dds_pkg::int_sample_t o_sample
);

    // Non-CORDIC paths need one extra delay stage because this module registers
    // the CORDIC valid/sample outputs before presenting the selected waveform.
    localparam int LATENCY = dds_pkg::WAVEFORM_LATENCY;
    localparam int SELECT_LATENCY = LATENCY + 1;

    // Primitive waveform outputs before latency alignment.
    logic                 sine_valid;
    dds_pkg::int_sample_t sine_sample;
    dds_pkg::int_sample_t square_sample;
    dds_pkg::int_sample_t triangle_sample;

    // Delayed selection state for non-CORDIC waveforms.
    dds_pkg::int_sample_t square_pipe_reg [0:SELECT_LATENCY-1];
    dds_pkg::int_sample_t triangle_pipe_reg [0:SELECT_LATENCY-1];
    dds_pkg::waveform_t   waveform_pipe_reg [0:SELECT_LATENCY-1];
    logic                 sample_valid_reg;
    dds_pkg::int_sample_t sample_reg;

    assign o_sample_valid = sample_valid_reg;
    assign o_sample       = sample_reg;

    // Cosine is generated by the same CORDIC but unused by this selector.
    dds_pkg::int_sample_t cos_sample_unused;

    cordic u_cordic (
        .i_clk(i_clk),
        .i_rst(i_rst),
        .i_phase_valid(i_phase_valid),
        .i_phase(i_phase),
        .o_sample_valid(sine_valid),
        .o_sin_sample(sine_sample),
        .o_cos_sample(cos_sample_unused)
    );

    square_generator u_square_generator (
        .i_phase(i_phase),
        .o_sample(square_sample)
    );

    triangle_generator u_triangle_generator (
        .i_phase(i_phase),
        .o_sample(triangle_sample)
    );

    int stage;

    // Alignment pipeline.
    // The waveform selection is delayed with the combinational waveforms so a
    // runtime waveform change takes effect on the sample computed from the same
    // input phase.
    always_ff @(posedge i_clk) begin
        if (i_rst) begin
            for (stage = 0; stage < SELECT_LATENCY; stage = stage + 1) begin
                square_pipe_reg[stage]   <= '0;
                triangle_pipe_reg[stage] <= '0;
                waveform_pipe_reg[stage] <= dds_pkg::WAVE_DC;
            end

            sample_reg       <= '0;
            sample_valid_reg <= 1'b0;
        end
        else begin
            square_pipe_reg[0]   <= square_sample;
            triangle_pipe_reg[0] <= triangle_sample;
            waveform_pipe_reg[0] <= i_waveform;

            for (stage = 0; stage < SELECT_LATENCY-1; stage = stage + 1) begin
                square_pipe_reg[stage+1]   <= square_pipe_reg[stage];
                triangle_pipe_reg[stage+1] <= triangle_pipe_reg[stage];
                waveform_pipe_reg[stage+1] <= waveform_pipe_reg[stage];
            end

            if (sine_valid) begin
                unique case (waveform_pipe_reg[SELECT_LATENCY-1])
                    dds_pkg::WAVE_DC:       sample_reg <= dds_pkg::INT_SAMPLE_MAX;
                    dds_pkg::WAVE_SINE:     sample_reg <= sine_sample;
                    dds_pkg::WAVE_SQUARE:   sample_reg <= square_pipe_reg[SELECT_LATENCY-1];
                    dds_pkg::WAVE_TRIANGLE: sample_reg <= triangle_pipe_reg[SELECT_LATENCY-1];
                    default:                sample_reg <= '0;
                endcase
            end
            else begin
                sample_reg <= '0;
            end

            sample_valid_reg <= sine_valid;
        end
    end

endmodule

`default_nettype wire
